### ISSUE TITLE
my gpg key updated

### ISSUE THREAD

**Issue by tonghuix** [beijinglug/warrant-canary#1]
new key id is ```F9EFC7D7C953EC9C```

Fingerprint ```BC80 1030 9D6B E9A4 44B0  3B29 F9EF C7D7 C953 EC9C```

**Comment by biergaizi** [comment]
The new key is used to sign https://github.com/beijinglug/warrant-canary/commit/232ecbe2c23ee887108bb296e834b27446765c11.
